namespace Plugin.Maui.TabbarBadge;

public static class AppBuilderExtensions
{
    /// <summary>
    /// Setup the TabbarBadge
    /// </summary>
    /// <param name="builder"><see cref="MauiAppBuilder"/> generated by <see cref="MauiApp"/> </param>
    /// <returns><see cref="MauiAppBuilder"/> configured for TabbarBadge</returns>
    public static MauiAppBuilder UseTabbarBadge(this MauiAppBuilder builder)
    {
        builder
            .ConfigureMauiHandlers(handlers =>
            {
#if ANDROID || IOS
                handlers.AddHandler<Shell, TabbarBadgeRenderer>();
#endif
            });

        return builder;
    }
}

